import type { Metadata } from 'next';
import './globals.css';
import { Inter, Oxanium } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';

const interHeading = Inter({ subsets: ['latin'], variable: '--font-heading' });

const oxanium = Oxanium({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        oxanium.variable,
        interHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {/* Navbar */}
        {/* <nav>Navbar</nav> */}
        {children}
        {/* Footer */}
        {/* <footer>Footer</footer> */}

        {/* Toaster */}
        <Toaster />
      </body>
    </html>
  );
}
